export function mapTransactionStatus(type: string): string | null {
  if (type === 'payment.approved') return 'paid'
  if (type === 'payment.paid') return 'paid'
  if (type === 'order.paid') return 'paid'
  if (type === 'charge.paid') return 'paid'
  if (type === 'payment.created') return 'created'
  if (type === 'order.created') return 'created'
  if (type === 'charge.created') return 'created'
  if (type === 'payment.pending') return 'pending'
  if (type === 'order.pending') return 'pending'
  if (type === 'charge.pending') return 'pending'
  if (type === 'payment.processing') return 'processing'
  if (type === 'charge.processing') return 'processing'
  if (type === 'payment.failed') return 'failed'
  if (type === 'order.payment_failed') return 'failed'
  if (type === 'charge.failed') return 'failed'
  if (type === 'payment.with_error' || type === 'charge.with_error' || type === 'order.with_error') return 'failed'
  if (type === 'payment.canceled' || type === 'payment.cancelled') return 'canceled'
  if (type === 'order.canceled' || type === 'order.cancelled') return 'canceled'
  if (type === 'charge.canceled' || type === 'charge.cancelled') return 'canceled'
  if (type === 'payment.expired' || type === 'order.expired' || type === 'charge.expired') return 'expired'
  if (type === 'payment.refunded') return 'refunded'
  if (type === 'charge.refunded') return 'refunded'
  return null
}
